dequelabs/cauldron-react

- package.json
- webpack.config.demo.js
- yarn.lock
This patch adds a `deploy` script which builds and deploys the demo app to GitHub pages. This can be done manually (`npm run deploy`), and will be done automagically after every successful release (`npm run release`).
> chore: add gh-pages deployment

- package.json
This patch replaces the npm `prepack` script with a `prepublishOnly` script. Using `prepublishOnly` is the preferred/recommended way of ensuring a build step is run before publishing to `npm`.
Closes #44.
> build: replace `prepack` with `prepublishOnly`

- demo/index.js
This patch updates the `<Router>`'s `basename` to handle being deployed to GitHub Pages. Previously (when deployed) the index wouldn't render since the router wouldn't match any routes.
> fix(demo): correct basename for GitHub pages

- demo/patterns/components/Checkbox/index.css
- demo/patterns/components/Checkbox/index.js
- src/lib/components/Checkbox/index.js
- test/src/components/Checkbox/index.js
* picks up on props.checked changes to support controlling checked state with internal state (see example below or in the demo code). Before, we only looked at props.checked initially (in the constructor), therefore updated values were essentially ignored
* adds a new `checkboxRef` prop
* updates demo/tests
```js
<Checkbox checked={this.state.checked} />
```
> feat: adds support for controlling checkbox with state

- .circleci/canary-version.js
- .circleci/config.yml
- README.md
- yarn.lock
This patch update the CircleCI configuration, enabling it to automatically publish all `master` commits as `@next` versions, and all SEMVER-ish tags as stable versions.
This should mean I no longer have to bug @schne324 every time I need something...
> ci: auto-publish to npm

- src/components/MenuItem/index.js
This patch adds an optional prop to the `<MenuItem>` component which will prevent it from automatically clicking links it contains. This is especially useful if the `<MenuItem>` contains a list of links.
Ref #73.
> feat: add option to disable "auto clicking" links

- types.d.ts
Realized I can't use the new prop until it's added to the TS definition.
I should really finish my TypeScript branch...
> fix: add missing `autoClickLink` prop to MenuItem ts def

- demo/index.js
- src/components/TopBar/TopBar.js
- test/src/components/TopBar/TopBar.js
This patch prevents the `<Topbar>` component from trying to "clone" falsy elements.
Closes #72
> fix(TopBar): support falsy children

- __tests__/src/components/FirstTimePointOut/index.js
- demo/patterns/components/FirstTimePointOut/index.js
- package.json
- src/components/FirstTimePointOut/index.js
- yarn.lock
Added `arrowPosition` prop to `<FirstTimePointOut />` component to allow arrow positions [via the deque pattern library](https://pattern-library.dequelabs.com/components/first-time-point).
Ref: #54
> feat: add prop to set arrow positions on first time point out

- __tests__/src/components/OptionsMenu/OptionsMenu.js
- __tests__/typechecks.tsx
- src/components/OptionsMenu/OptionsMenu.js
- types.d.ts
`<OptionsMenu>` now has an `onSelect` prop that passes the event for the element that was selected.
Ref: #58
> feat: add onSelect func prop to OptionsMenu

- __tests__/src/components/OptionsMenu/OptionsMenu.js
- __tests__/typechecks.tsx
- src/components/OptionsMenu/OptionsMenu.js
- types.d.ts
New prop `closeOnSelect` added to `<OptionsMenu />`.
I set the default to be `true` since it seems to be more common that you would want to close the menu than not. This behavior can be opted out of across the menu by setting it to `false` _or_ by preventing the default event.
Ref: #59
> feat: add closeOnSelect prop to OptionsMenu

- __tests__/src/components/ClickOutsideListener/index.js
- __tests__/src/components/Modal/index.js
- __tests__/src/components/OptionsMenu/OptionsMenu.js
- __tests__/src/components/SideBar/index.js
- __tests__/typechecks.tsx
- demo/index.js
- demo/patterns/components/ClickOutsideListener/index.js
- demo/patterns/components/OptionsMenu/index.js
- src/components/ClickOutsideListener/index.js
- src/components/Modal/index.js
- src/components/OptionsMenu/OptionsMenu.js
- src/components/SideBar/index.js
- src/index.js
- types.d.ts
* New Component: `<ClickOutsideListener />`
* Has `onClickOutside` prop to allow actions to handle `click`/`touch` events outside of children
* Set event to listen to (i.e. `mouseup`, `touchstart`) with `mouse/touchEvent` prop or set to `false` to prevent completely
Evaluated both [tj/react-click-outside](https://github.com/tj/react-click-outside) and [airbnb/react-outside-click-handler](https://github.com/airbnb/react-outside-click-handler). The former is only available from GitHub and mounts to an empty `<div>` which seems undesirable. The latter is nearly [10kb min + gzipped](https://bundlephobia.com/result?p=react-outside-click-handler@1.2.3) which seems extremely undesirable for such a small component.
Ref: #57 
Closes: #84
> feat: add ClickOutsideListener component to capture outside of children events

- README.md
This patch removes the extremely unfriendly/unwelcoming message about this project. I don't know why it's here and feel that it's the wrong direction we should be taking our OSS repositories.
I'm happy to take on the responsibility of answering questions, addressing feature requests and looking at bug reports if everyone else is "too busy" to do so.
> docs: Remove unfriendly disclaimer message

- demo/index.js
- src/components/MenuItem/index.js
When the sidebar was collapsed, `<ClickOutsideListener>` was triggering on the toggle button in the menu since the menu would first open then bubble up to the click outside immediately closing preventing the user from being able to open the sidebar.
> fix: demo unable to open sidebar when collapsed

- __tests__/src/components/OptionsMenu/OptionsMenu.js
- src/components/OptionsMenu/OptionsMenu.js
Links should be clicked when inside of `<OptionsMenuItem>`. This does not address any issues with `<MenuItem>`.
Ref: #73
> fix: click nested links inside OptionsMenuItem

- __tests__/src/components/TopBar/TopBar.js
- src/components/TopBar/TopBar.js
Falsy children were being included as part of the focus calculations when being mapped. `menuItems` should only contain items that actually exist in the DOM.
Closes: #104
> fix: falsy children in TopBar preventing correct focus navigation

- __tests__/src/components/Toast/index.js
- demo/patterns/components/Toast/index.js
- src/components/Toast/index.js
`<Toast>` should now show/hide based on `show` prop alone. 
Ref: #28
> fix: push state upwards in Toast and refactor deprecated method

- package.json
- yarn.lock
This patch makes our `classnames` dependency a production dependency (rather than a development dependency). This is needed as [the package is used at runtime](https://github.com/dequelabs/cauldron-react/blob/v0.5.1/src/components/Button/index.js#L3).
> fix: mark `classnames` as a production dependency

- __tests__/src/components/ExpandCollapsePanel/ExpandCollapsePanel.js
- src/components/ExpandCollapsePanel/ExpandCollapsePanel.js
- types.d.ts
I noticed that occasionally an element could flicker as an animation was being queued and then immediately removed if the timing was set to `0`. This fixes that by only queueing animation styles when an animation is set to run.
> fix: don't run animations when animationTiming is not set

- __tests__/src/components/ExpandCollapsePanel/ExpandCollapsePanel.js
- src/components/ExpandCollapsePanel/ExpandCollapsePanel.js
My assertions weren't actually running, which led me to believe my original changes were working correctly. 🤦‍♂
* Use `dqpl-hidden` class as visibility check as deque-pattern-library's style aren't included in jest's dom
* Fix issue where a panel being re-closed with `0` animation time was not actually hidden.
* Clean-up tests and actually run assertions
> fix: actually run assertions in tests for expand/collapse component

- __tests__/src/components/OptionsMenu/OptionsMenu.js
- src/components/OptionsMenu/OptionsMenu.js
MenuItem's class was getting clobbered, my guess is we probably don't want to overwrite the existing class but just append it.
> fix: allow classnames to be added to existing menuitem class

- __tests__/src/components/OptionsMenu/OptionsMenu.js
- src/components/OptionsMenu/OptionsMenu.js
Falsy children were being rendered in `<OptionsMenu>` causing there to be ghost menu items inside of the list allow for mouse/keyboard interactions.
> fix: don't render falsy children in OptionsMenu

- __tests__/src/components/OptionsMenu/OptionsMenuItem.js
- __tests__/typechecks.tsx
- src/components/OptionsMenu/OptionsMenu.js
- src/components/OptionsMenu/OptionsMenuItem.js
- types.d.ts
Attest currently allows MenuItems to be disabled.
This functionality was formally handled inside of dropdown of _dqpl-react_, but since we're moving things over to cauldron just replicating the functionality here. In addition, adding an `onSelect` property to match the `onSelect` callback of `<OptionsMenu>`. When disabled, this event should not fire.
> feat: allow OptionsMenuItem to be disabled

- __tests__/src/components/OptionsMenu/OptionsMenu.js
- __tests__/src/components/OptionsMenu/OptionsMenuItem.js
- __tests__/src/components/OptionsMenu/OptionsMenuList.js
- __tests__/src/components/OptionsMenu/OptionsMenuTrigger.js
- __tests__/src/components/TopBar/TopBarMenu.js
- __tests__/typechecks.tsx
- demo/index.js
- demo/patterns/components/OptionsMenu/index.js
- src/components/OptionsMenu/OptionsMenu.js
- src/components/OptionsMenu/OptionsMenuList.js
- src/components/OptionsMenu/OptionsMenuTrigger.js
- src/components/OptionsMenu/OptionsMenuWrapper.js
- src/components/OptionsMenu/index.css
- src/components/OptionsMenu/index.js
- src/components/TopBar/TopBarMenu.js
- src/index.css
- src/index.js
- types.d.ts
Split the existing `OptionsMenu` into:
* *Uncontrolled* Component: `<OptionsMenu>` 
* `<OptionsMenuList>` for managing list state.
Prior to this change, the `<OptionsMenu>` component was controlled meaning that any consumers were required to manage state. By converting the component to an uncontrolled component, consumers are no longer required to manage state.
**Example**
```
<OptionsMenu
align="left"
trigger={triggerProps => (
<OptionsMenuTrigger {...triggerProps}>
<Icon type="fa-ellipsis-v" label="Options" />
</OptionsMenuTrigger>
)}
>
<OptionsMenuItem>This</OptionsMenuItem>
<OptionsMenuItem>That</OptionsMenuItem>
<OptionsMenuItem>The third</OptionsMenuItem>
<OptionsMenuItem disabled>And the other</OptionsMenuItem>
</OptionsMenu>
```
**_Other Changes_**
* Fixed: Button/Menu states …
> feat: split OptionsMenu into List and controlled component

- package.json
We're using `React.memo()` so bumping the peer version.
> chore: set react peer version to 16.6

- __tests__/src/components/OptionsMenu/OptionsMenuList.js
- src/components/OptionsMenu/OptionsMenuList.js
React's synthetic event handling was preventing us from stopping the devtools console panel from toggling (dequelabs/attest-browser-extensions#310) when closing a menu with <kbd>esc</kbd>. To bypass this and allow us to manually prevent this in the extension we're instead attaching `keydown` natively to the element.
Closes: #150
> fix: use native keyDown event for optionsmenu instead of React's synthetic event system

- __tests__/src/components/ExpandCollapsePanel/ExpandCollapsePanel.js
- demo/patterns/components/ExpandCollapsePanel/index.js
- src/components/ExpandCollapsePanel/ExpandCollapsePanel.js
- types.d.ts
Allows for `<ExpandCollapsePanel />` to be controlled with an optional `open` prop.
Needed for dequelabs/attest-browser-extensions#716.
Closes #153
> feat: allow expand/collapse component to be controlled

- .circleci/config.yml
- README.md
This patch changes our workflow a bit, making it mirror pretty much every other repository we have. Once this is approved, I'll swap the default branch to "develop" and we'll begin working from it.
Releases are still handled by CircleCI, the only difference is `develop` commits result in `@next` being published and `master` commits publish `@latest`. There is no longer any CI magic for SEMVER-ish tags.
> ci: publish @next from develop, @latest from master

- __tests__/src/components/FirstTimePointOut/index.js
- __tests__/src/utils/remove-ids/index.js
- demo/patterns/components/FirstTimePointOut/index.js
- src/components/FirstTimePointOut/index.js
- src/utils/remove-ids/index.js
I realized that the targeted FTPO had duplicate ids due to `children` being rendered twice. This adds a util to remove those ids from the visible FTPO only when it's being duplicated to a portal.
> fix: remove duplicate ids from visible FTPO

- types.d.ts
The `Select` component's `onSelect` callback receives a `SelectOption`, not a "value".
> fix(Select): correct `onSelect` TypeScript definition

- demo/patterns/components/Select/index.js
- src/components/Select/index.js
This patch prevents the `<button>` used within `<Select>` from submitting a `<form>`. The button would submit the form because its [`type` attribute was not specified and the default type is "_submit_"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type). By setting `type="button"`, we prevent the form submission.
Closes #188 and #186
> fix(Select): prevent unwanted <form> submissions 

- package.json
- yarn.lock
This patch upgrades TypeScript to v3.5, enabling the usage of the [`Omit` helper type](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html#the-omit-helper-type).
This blocks #191.
> chore: upgrade TypeScript to v3.5

- __tests__/typechecks.tsx
- types.d.ts
This patch enables standard `HTMLInputElement` properties on our `TextField` component.
> fix(TextField): properly implement `HTMLInputElement` props

- demo/index.css
- package.json
- src/components/FirstTimePointOut/index.css
- yarn.lock
Updates to latest pattern library with smaller arrow size and re-adjusts the auto ftpo targeted positioning based on the smaller arrow size.
BREAKING CHANGE: FTPOs have new positioning and layout due to smaller arrows
Ref: dequelabs/pattern-library#124
Ref: dequelabs/pattern-library#118
**Required fields, to be filled out by PR reviewer(s)**
> feat: implement smaller ftpo arrows from pattern-library
